### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(FoxStealer)
add_subdirectory(FoxStealerContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    FoxStealerplugin
    FoxStealerContentplugin)